# Generated by Django 4.0.5 on 2022-06-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_alter_comment_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='to',
            new_name='from_email',
        ),
    ]
